# Canvas Colors
canvas.node.radius=20
canvas.node.color=#16a34a
canvas.node.edge-source.color=#4ade80
canvas.node.selected.color=#f59e0b
canvas.edge.color=#166534
canvas.edge.selected.color=#60a5fa
canvas.label.color=#f0fdf4
canvas.background=#020c05
canvas.grid.color=#0d2b14
