pair.save=INSERT INTO graph_pairs (name, user_id, graph_a_id, graph_b_id) VALUES (?, ?, ?, ?)
pair.loadByUser=SELECT * FROM graph_pairs WHERE user_id = ?
pair.delete=DELETE FROM graph_pairs WHERE id = ?
