graph.save=INSERT INTO graphs (name, user_id) VALUES (?, ?)
graph.load=SELECT * FROM graphs WHERE id = ?
graph.loadByUser=SELECT * FROM graphs WHERE user_id = ?
graph.delete=DELETE FROM graphs WHERE id = ?
